package entities;
// Generated Mar 21, 2015 9:28:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StudentVolunteers generated by hbm2java
 */
public class StudentVolunteers  implements java.io.Serializable {


     private Integer id;
     private int studentId;
     private String organization;
     private String role;
     private String cause;
     private Date startTime;
     private Date finishTime;
     private Integer isNow;
     private String more;

    public StudentVolunteers() {
    }

	
    public StudentVolunteers(int studentId) {
        this.studentId = studentId;
    }
    public StudentVolunteers(int studentId, String organization, String role, String cause, Date startTime, Date finishTime, Integer isNow, String more) {
       this.studentId = studentId;
       this.organization = organization;
       this.role = role;
       this.cause = cause;
       this.startTime = startTime;
       this.finishTime = finishTime;
       this.isNow = isNow;
       this.more = more;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(String organization) {
        this.organization = organization;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getCause() {
        return this.cause;
    }
    
    public void setCause(String cause) {
        this.cause = cause;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getFinishTime() {
        return this.finishTime;
    }
    
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }
    public Integer getIsNow() {
        return this.isNow;
    }
    
    public void setIsNow(Integer isNow) {
        this.isNow = isNow;
    }
    public String getMore() {
        return this.more;
    }
    
    public void setMore(String more) {
        this.more = more;
    }




}


