package entities;
// Generated Mar 21, 2015 9:28:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StudentPosts generated by hbm2java
 */
public class StudentPosts  implements java.io.Serializable {


     private Integer id;
     private int studentId;
     private String content;
     private Date time;

    public StudentPosts() {
    }
    public StudentPosts(int studentId) {
        this.studentId = studentId;
    }
    public StudentPosts(int studentId, String content, Date time) {
       this.studentId = studentId;
       this.content = content;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


