package entities;
// Generated Mar 21, 2015 9:28:13 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StudentBasic generated by hbm2java
 */
public class StudentBasic  implements java.io.Serializable {


     private Integer id;
     private int studentId;
     private Date birthday;
     private String gender;
     private String college;
     private Integer inYear;
     private String major;
     private String maritalStatus;
     private String nation;
     private String more;

    public StudentBasic() {
    }

	
    public StudentBasic(int studentId) {
        this.studentId = studentId;
    }
    public StudentBasic(int studentId, Date birthday, String gender, String college, Integer inYear, String major, String maritalStatus, String nation, String more) {
       this.studentId = studentId;
       this.birthday = birthday;
       this.gender = gender;
       this.college = college;
       this.inYear = inYear;
       this.major = major;
       this.maritalStatus = maritalStatus;
       this.nation = nation;
       this.more = more;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getCollege() {
        return this.college;
    }
    
    public void setCollege(String college) {
        this.college = college;
    }
    public Integer getInYear() {
        return this.inYear;
    }
    
    public void setInYear(Integer inYear) {
        this.inYear = inYear;
    }
    public String getMajor() {
        return this.major;
    }
    
    public void setMajor(String major) {
        this.major = major;
    }
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }
    public String getNation() {
        return this.nation;
    }
    
    public void setNation(String nation) {
        this.nation = nation;
    }
    public String getMore() {
        return this.more;
    }
    
    public void setMore(String more) {
        this.more = more;
    }




}


