package entities;
// Generated Mar 21, 2015 9:28:13 PM by Hibernate Tools 4.3.1



/**
 * StudentCertifications generated by hbm2java
 */
public class StudentCertifications  implements java.io.Serializable {


     private Integer id;
     private int studentId;
     private String certification;
     private Integer year;

    public StudentCertifications() {
    }

	
    public StudentCertifications(int studentId) {
        this.studentId = studentId;
    }
    public StudentCertifications(int studentId, String certification, Integer year) {
       this.studentId = studentId;
       this.certification = certification;
       this.year = year;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getCertification() {
        return this.certification;
    }
    
    public void setCertification(String certification) {
        this.certification = certification;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }




}


