package entities;
// Generated Mar 21, 2015 9:28:13 PM by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private String type;
     private String username;
     private String email;
     private String password;
     private String fullname;
     private String phone;
     private String address;
     private String avatar;
     private Integer lastLogin;
     private Integer lastActivity;
     private String activation;

    public Users() {
    }

	
    public Users(String type, String username, String email, String password) {
        this.type = type;
        this.username = username;
        this.email = email;
        this.password = password;
    }
    public Users(String type, String username, String email, String password, String fullname, String phone, String address, String avatar, Integer lastLogin, Integer lastActivity, String activation) {
       this.type = type;
       this.username = username;
       this.email = email;
       this.password = password;
       this.fullname = fullname;
       this.phone = phone;
       this.address = address;
       this.avatar = avatar;
       this.lastLogin = lastLogin;
       this.lastActivity = lastActivity;
       this.activation = activation;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public Integer getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Integer lastLogin) {
        this.lastLogin = lastLogin;
    }
    public Integer getLastActivity() {
        return this.lastActivity;
    }
    
    public void setLastActivity(Integer lastActivity) {
        this.lastActivity = lastActivity;
    }
    public String getActivation() {
        return this.activation;
    }
    
    public void setActivation(String activation) {
        this.activation = activation;
    }




}


