package entities;
// Generated Apr 19, 2015 6:47:22 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer id;
     private int postId;
     private int userId;
     private String content;
     private int likes;
     private Date time;

    public Comments() {
    }

    public Comments(int postId, int userId, String content, int likes, Date time) {
       this.postId = postId;
       this.userId = userId;
       this.content = content;
       this.likes = likes;
       this.time = time;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getPostId() {
        return this.postId;
    }
    
    public void setPostId(int postId) {
        this.postId = postId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public int getLikes() {
        return this.likes;
    }
    
    public void setLikes(int likes) {
        this.likes = likes;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


