package entities;
// Generated Apr 18, 2015 10:25:58 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Jobs generated by hbm2java
 */
public class Jobs  implements java.io.Serializable {


     private Integer jobId;
     private String jobTitle;
     private int conpanyId;
     private String requirement;
     private String quantity;
     private String salary;
     private Date deadline;
     private String more;

    public Jobs() {
    }

	
    public Jobs(String jobTitle, int conpanyId) {
        this.jobTitle = jobTitle;
        this.conpanyId = conpanyId;
    }
    public Jobs(String jobTitle, int conpanyId, String requirement, String quantity, String salary, Date deadline, String more) {
       this.jobTitle = jobTitle;
       this.conpanyId = conpanyId;
       this.requirement = requirement;
       this.quantity = quantity;
       this.salary = salary;
       this.deadline = deadline;
       this.more = more;
    }
   
    public Integer getJobId() {
        return this.jobId;
    }
    
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public int getConpanyId() {
        return this.conpanyId;
    }
    
    public void setConpanyId(int conpanyId) {
        this.conpanyId = conpanyId;
    }
    public String getRequirement() {
        return this.requirement;
    }
    
    public void setRequirement(String requirement) {
        this.requirement = requirement;
    }
    public String getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }
    public String getSalary() {
        return this.salary;
    }
    
    public void setSalary(String salary) {
        this.salary = salary;
    }
    public Date getDeadline() {
        return this.deadline;
    }
    
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }
    public String getMore() {
        return this.more;
    }
    
    public void setMore(String more) {
        this.more = more;
    }

}


