package entities;
// Generated 31-Mar-2015 00:53:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StudentExp generated by hbm2java
 */
public class StudentExp  implements java.io.Serializable {


     private Integer id;
     private int studentId;
     private String company;
     private String title;
     private Date startTime;
     private Date finishTime;
     private String more;

    public StudentExp() {
    }

	
    public StudentExp(int studentId) {
        this.studentId = studentId;
    }
    public StudentExp(int studentId, String company, String title, Date startTime, Date finishTime, String more) {
       this.studentId = studentId;
       this.company = company;
       this.title = title;
       this.startTime = startTime;
       this.finishTime = finishTime;
       this.more = more;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getCompany() {
        return this.company;
    }
    
    public void setCompany(String company) {
        this.company = company;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getFinishTime() {
        return this.finishTime;
    }
    
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }
    public String getMore() {
        return this.more;
    }
    
    public void setMore(String more) {
        this.more = more;
    }




}


