package entities;
// Generated 31-Mar-2015 00:53:37 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StudentPosts generated by hbm2java
 */
public class StudentPosts  implements java.io.Serializable {


     private Integer id;
     private int studentId;
     private String content;
     private Date time;
     private int likes;
     private int comments;
     private int shares;

    public StudentPosts() {
    }

	
    public StudentPosts(int studentId, int likes, int comments, int shares) {
        this.studentId = studentId;
        this.likes = likes;
        this.comments = comments;
        this.shares = shares;
    }
    public StudentPosts(int studentId, String content, Date time, int likes, int comments, int shares) {
       this.studentId = studentId;
       this.content = content;
       this.time = time;
       this.likes = likes;
       this.comments = comments;
       this.shares = shares;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public int getLikes() {
        return this.likes;
    }
    
    public void setLikes(int likes) {
        this.likes = likes;
    }
    public int getComments() {
        return this.comments;
    }
    
    public void setComments(int comments) {
        this.comments = comments;
    }
    public int getShares() {
        return this.shares;
    }
    
    public void setShares(int shares) {
        this.shares = shares;
    }




}


