package entities;
// Generated 31-Mar-2015 00:53:37 by Hibernate Tools 4.3.1



/**
 * StudentInterests generated by hbm2java
 */
public class StudentInterests  implements java.io.Serializable {


     private Integer id;
     private int studentId;
     private String interest;

    public StudentInterests() {
    }

	
    public StudentInterests(int studentId) {
        this.studentId = studentId;
    }
    public StudentInterests(int studentId, String interest) {
       this.studentId = studentId;
       this.interest = interest;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getInterest() {
        return this.interest;
    }
    
    public void setInterest(String interest) {
        this.interest = interest;
    }




}


