package entities;
// Generated 31-Mar-2015 00:53:37 by Hibernate Tools 4.3.1



/**
 * StudentLanguages generated by hbm2java
 */
public class StudentLanguages  implements java.io.Serializable {


     private Integer id;
     private int studentId;
     private String language;
     private Integer level;

    public StudentLanguages() {
    }

	
    public StudentLanguages(int studentId) {
        this.studentId = studentId;
    }
    public StudentLanguages(int studentId, String language, Integer level) {
       this.studentId = studentId;
       this.language = language;
       this.level = level;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getLanguage() {
        return this.language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }




}


