package entities;
// Generated 31-Mar-2015 00:53:37 by Hibernate Tools 4.3.1



/**
 * StudentStudyings generated by hbm2java
 */
public class StudentStudyings  implements java.io.Serializable {


     private Integer id;
     private Integer studentId;
     private String className;
     private Float score;
     private String conduct;

    public StudentStudyings() {
    }

    public StudentStudyings(Integer studentId, String className, Float score, String conduct) {
       this.studentId = studentId;
       this.className = className;
       this.score = score;
       this.conduct = conduct;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }
    public Float getScore() {
        return this.score;
    }
    
    public void setScore(Float score) {
        this.score = score;
    }
    public String getConduct() {
        return this.conduct;
    }
    
    public void setConduct(String conduct) {
        this.conduct = conduct;
    }




}


