package entities;
// Generated 31-Mar-2015 00:53:37 by Hibernate Tools 4.3.1



/**
 * StudentSkills generated by hbm2java
 */
public class StudentSkills  implements java.io.Serializable {


     private Integer id;
     private int studentId;
     private String skill;
     private Integer level;

    public StudentSkills() {
    }

	
    public StudentSkills(int studentId) {
        this.studentId = studentId;
    }
    public StudentSkills(int studentId, String skill, Integer level) {
       this.studentId = studentId;
       this.skill = skill;
       this.level = level;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public String getSkill() {
        return this.skill;
    }
    
    public void setSkill(String skill) {
        this.skill = skill;
    }
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }




}


