<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Image carousel generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Image carousel" />
	
	<!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
	<link rel="stylesheet" type="text/css" href="<%=request.getContextPath()%>/imageSliderData/engines/style.css" />
	<script type="text/javascript" src="<%=request.getContextPath()%>/imageSliderData/engines/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
	
</head>
<body style="background-color:#d7d7d7;margin:0">

	<!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
		<li><img src="<%=request.getContextPath()%>/imageSliderData/images/1.jpg" alt="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam" title="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam" id="wows1_0"/></li>
		<li><img src="<%=request.getContextPath()%>/imageSliderData/images/2.jpg" alt="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam" title="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam" id="wows1_1"/></li>
		<li><img src="<%=request.getContextPath()%>/imageSliderData/images/3.jpg" alt="Cùng chúng tôi" title="Cùng chúng tôi" id="wows1_2"/></li>
		<li><img src="<%=request.getContextPath()%>/imageSliderData/images/4.jpg" alt="full screen slider" title="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam" id="wows1_3"/></li>
		<li><img src="<%=request.getContextPath()%>/imageSliderData/images/5.jpg" alt="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam" title="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam" id="wows1_4"/></li>
	</ul></div>
	<div class="ws_bullets">
		<div>
			<a href="#" title="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam"><img src="<%=request.getContextPath()%>/imageSliderData/tooltips/1.jpg" alt="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam"/>1</a>
			<a href="#" title="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam"><img src="<%=request.getContextPath()%>/imageSliderData/tooltips/2.jpg" alt="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam"/>2</a>
			<a href="#" title="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam"><img src="<%=request.getContextPath()%>/imageSliderData/tooltips/3.jpg" alt="Cùng chúng tôi"/>3</a>
			<a href="#" title="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam"><img src="<%=request.getContextPath()%>/imageSliderData/tooltips/4.jpg" alt="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam"/>4</a>
			<a href="#" title="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam"><img src="<%=request.getContextPath()%>/imageSliderData/tooltips/5.jpg" alt="Cùng chúng tôi xây dựng mạng xã hội việc làm dành cho sinh viên lớn nhất Việt  Nam"/>5</a>
		</div>
	</div>
	<div class="ws_shadow"></div>
	</div>	
	<script type="text/javascript" src="<%=request.getContextPath()%>/imageSliderData/engines/wowslider.js"></script>
	<script type="text/javascript" src="<%=request.getContextPath()%>/imageSliderData/engines/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
	
</body>
</html>